version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: my_db
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: my_django
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1,0.0.0.0
      DJANGO_SECRET_KEY: "supersecret"
      DJANGO_DEBUG: "True"

      DB_NAME: mydb
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_HOST: db
      DB_PORT: 3306
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
