version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: my_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: messenger_db
      MYSQL_USER: messenger_user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: my_django
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "80:8000"
    environment:
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DJANGO_SETTINGS_MODULE: messanger.settings
      DB_NAME: messenger_db
      DB_USER: messenger_user
      DB_PASSWORD: userpass
      DB_HOST: db
      DB_PORT: 3306
    depends_on:
      - db

volumes:
  db_data:
